### ISSUE TITLE
Add Google Authentication

### ISSUE THREAD

**Issue by bkb-Git** [marvelai-org/marvel-platform#80]
### Description
Enhance the existing authentication system by adding the option for users to sign in and sign up using their Google accounts. This will provide an additional, convenient authentication method.

![image](https://github.com/user-attachments/assets/7cf7d162-50c8-4740-b934-efde577b892d)

### Tasks
1. **Enable Google Authentication in Firebase**:
   - Go to the Firebase Console and enable Google Authentication.
2. **Install Firebase Dependencies**:
   - Ensure the `firebase` package is installed and up-to-date.
3. **Configure Firebase for Google Auth**:
   - Update the Firebase configuration to include the Google Auth provider.
4. **Add Google Sign-In Button to `SignInForm.jsx`**:
   - Add a Google Sign-In button to the `SignInForm.jsx` component.
   - Style the button to match the application's theme.
5. **Add Google Sign-Up Button to `SignUpForm.jsx`**:
   - Add a Google Sign-Up button to the `SignUpForm.jsx` component.
   - Style the button to match the application's theme.
6. **Implement Google Sign-In/Sign-Up Logic**:
   - Implement the sign-in and sign-up logic using Firebase Auth's Google provider.
   - Handle success and error scenarios appropriately.
7. **Update Authentication State**:
   - Update the Redux store or context to reflect the user's authentication state.
   - Ensure the UI updates correctly based on the authentication state.
8. **Testing**:
   - Thoroughly test the Google Sign-In and Sign-Up functionality on different devices and browsers.
   - Ensure that sign-in, sign-up, and error handling work as expected.

### Files and Locations
- **`SignInForm.jsx`**: Add the Google Sign-In button and logic.
- **`SignUpForm.jsx`**: Add the Google Sign-Up button and logic.
- **Firebase Configuration**: Ensure the Firebase configuration file is correctly set up (e.g., `firebaseConfig.js`).

### Acceptance Criteria
- [ ] Google Authentication is enabled and working for both sign-in and sign-up.
- [ ] Users can sign in and sign up using their Google accounts.
- [ ] Authentication state updates correctly in the application.
- [ ] Thorough testing is completed, and all edge cases are handled.

### Additional Information
- **Firebase Console**: Ensure Google Authentication is enabled in the [Firebase Console](https://console.firebase.google.com/).
- **Firebase Documentation**: Refer to the [Firebase Authentication Documentation](https://firebase.google.com/docs/auth/web/google-signin) for implementation details.

### References
- **Current Authentication Setup**: Review the current email and password authentication setup in `SignInForm.jsx` and `SignUpForm.jsx` to integrate Google Sign-In seamlessly.

---

### Example Code Snippet for Google Sign-In/Sign-Up

```javascript
import { getAuth, signInWithPopup, GoogleAuthProvider } from "firebase/auth";
import { useDispatch } from "react-redux";
import { setUser } from "./userSlice"; // Example Redux action to set the user

const auth = getAuth();
const provider = new GoogleAuthProvider();

const handleGoogleSignIn = async () => {
  try {
    const result = await signInWithPopup(auth, provider);
    const user = result.user;
    // Dispatch user data to Redux store or update context
    dispatch(setUser(user));
  } catch (error) {
    console.error("Error signing in with Google: ", error);
  }
};

// In your SignInForm.jsx and SignUpForm.jsx
<button onClick={handleGoogleSignIn}>Sign in with Google</button>
<button onClick={handleGoogleSignIn}>Sign up with Google</button>

**Comment by aravindinduri** [comment]
can i work on this
